#!/usr/bin/env python
import sys
from js2coffee import build, Unsupported, SyntaxError_

if __name__ == "__main__":
  if len(sys.argv) == 1:
    print "Usage: %s file.js" % sys.argv[0]
    exit()

  try:
    data = file(sys.argv[1]).read()
    out  = build(data)
    print out

  except SyntaxError_ as e:
    print e
